version: "3"
services:
  web:
    image: jamtur01/composeapp
    ports:
      - "5002:5000"
    volumes:
      - .:/composeapp
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
