# Generated by Django 5.1.7 on 2025-05-08 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_event', models.DateField()),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Handball', 'Handball')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=199)),
                ('year_of_birth', models.IntegerField()),
                ('total_games_played', models.IntegerField()),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank', models.CharField(choices=[('A', 'Amateur'), ('P', 'Professional')], max_length=1)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Handball', 'Handball')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Handball', 'Handball')], max_length=20)),
                ('coach_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event.event')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event.participation')),
            ],
        ),
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event.participation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_event.team')),
            ],
        ),
    ]
